### PR TITLE
Add shorten wiki

### LINKED ISSUE #40: Shorten wiki links
Example:

```
https://github.com/refined-github/refined-github/wiki/%22Can-you-add-this-feature%3F%22#3-it-doesnt-require-options
```

Native:

- https://github.com/refined-github/refined-github/wiki/%22Can-you-add-this-feature%3F%22#3-it-doesnt-require-options

Ideal:

- [refined-github/refined-github (wiki) "Can you add this feature?" (3 it doesnt require options)](https://github.com/refined-github/refined-github/wiki/%22Can-you-add-this-feature%3F%22#3-it-doesnt-require-options)

### PR DESCRIPTION
**Pull request by Katsute**
Closes #40

### CODE REVIEW

**Comment by Katsute** [comment]
I'm not sure why the linter is failing, fails on `main` as well

**Comment by fregante** [comment]
Thank you! The linter is failing due to a bug, it needs to be updated in a separate PR to at least 0.55 or 0.45.1 if I remember correctly

**Comment by fregante** [comment]
You can run `npx xo --fix`

**Comment by Katsute** [comment]
Fixed 🎉

**Review by fregante — APPROVED** [review]
LGTM but I'm hoping to hear from other reviewers. Does this format make sense? I'm thinking maybe:

> Wiki: title blah blah (repo)

**Comment by fregante** [comment]
Can you change the format to the suggested one?

**Pull request merged**
