### PR TITLE
Restore support for `https://github.com` exception

### PR DESCRIPTION
**Pull request by kovsu**
Test URL:

https://github.com/download-directory/download-directory.github.io/issues/143

image

### CODE REVIEW

**Comment by kovsu** [comment]
As you can see if url is `https://github.com/`, `shortenRepoUrl` function runs to end. Because these properties is empty, so it returns an empty string and makes the link is swallowed,

https://github.com/refined-github/shorten-repo-url/blob/ce4fcc4b5632cf24523ed11e73da5ff876466b36/index.js#L274-L276

**Comment by kovsu** [comment]
If we get the pathname is `/`, it goes to here.

https://github.com/refined-github/shorten-repo-url/blob/ce4fcc4b5632cf24523ed11e73da5ff876466b36/index.js#L159-L178

so we will get a cleanHref that is `github.com`

**Comment by kovsu** [comment]
@fregante Please review ~

**Comment by kovsu** [comment]
image

**Comment by kovsu** [comment]
@fregante Should I merge this? I think you forget this.

**Comment by fregante** [comment]
I thought I commented 😅 yes you can.

Also a new patch version can be released

**Pull request merged**
