### PR TITLE
Bump xo from 0.52.3 to 0.56.0

### PR DESCRIPTION
**Pull request by Katsute**
Bumps [xo](https://github.com/xojs/xo) from 0.52.3 to 0.56.0

Fix string replace all

### CODE REVIEW

**Comment by yakov116** [comment]
Why not fix the issue?

**Comment by Katsute** [comment]
The code was already using `replace` before the linter broke, I just assumed that we would want to keep the linter the same as before.

**Comment by fregante** [comment]
I'd rather fix the issue, it's autofixable

**Review by fregante — APPROVED** [review]

**Comment by fregante** [comment]
Thank you!

**Pull request merged**
